# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configures the configuration version 2
Vagrant.configure("2") do |config|

    # Box settings. boxes at https://vagrantcloud.com/search.
    config.vm.box = "ubuntu/trusty64"
  
    # Disable the auto-update feature of the vagrant
    config.vm.box_check_update = "false"
  
    # Provider Settings
    config.vm.provider "virtualbox" do |vb|
  
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
  
      # Customize the amount of memory of VM. whichever VM we are going to define and create from this Vagrantfile will be having 2048mb
      vb.memory = 2048
  
      # Customize the amount of CPU
      vb.cpus = 2
  
    end
  
    # Defining a New VM named docker-server and assign to the variable named docker 
    config.vm.define "minikube-server" do |minikube| 
  
      # Set the hostname of the VM 
      minikube.vm.hostname = "minikube-server.lab.local" 
      
      # Setting the box (OS) for the Virtual machine, we use ubuntu 
      minikube.vm.box = "bento/ubuntu-20.04" 

      # Shared forlder Settings between host and guest VM 
      minikube.vm.synced_folder "./lab_data", "/lab_data", :mount_options => ["dmode=775", "fmode=664"]

    end
  
  end
  